---
title: "The RI-CLPM & Extensions"
toc: false
doi: 10.1080/10705511.2020.1784738
author:
  - name: Jeroen D. Mulder
    orcid: 0000-0002-5553-0856
    url: 
    affiliations:
      - Utrecht University
  - name: Ellen L. Hamaker
    affiliations:
      - Utrecht University
bibliography: references.bib
---

This website is a supplement to "Three Extensions of the Random Intercept Cross-Lagged Panel Model" by @mulder_three_2021. It contains Mplus syntax and *lavaan* code for specifying the basic RI-CLPM and the following three extensions:

1. including a time-invariant predictor and outcome,
2. doing multiple group analysis, and
3. using multiple indictors for variables. 

Use the top menu to navigate to the [Mplus syntax](https://jeroendmulder.github.io/RI-CLPM/mplus.html), [*lavaan* code](https://jeroendmulder.github.io/RI-CLPM/lavaan.html), [News](https://jeroendmulder.github.io/RI-CLPM/news.html), or [Frequently Asked Questions (FAQ)](https://jeroendmulder.github.io/RI-CLPM/faq.html). The *lavaan (R)* tab contains additional code for performing the $\bar{\chi}^{2}$-test (chi-bar-square test) in R. This test is used for comparing nested models where the more parsimonious model is based on constraining parameters on the bound of the parameter space (e.g., constraining a variance to 0). The *News* tab documents important updates and additions to the Mplus syntax, *lavaan* model syntax, or the FAQ on this website.  

### Data
You can find simulated example data sets (1189 units, 5 repeated-measures) on [GitHub](https://github.com/jeroendmulder/RI-CLPM/tree/master/data) to get hands-on experience with this modeling approach. The example data are motivated by @narmandakh_bidirectional_2020, who obtained 5 waves of data from 1189 adolescents on their sleep problems and anxiety over 15 years.
