---
title: "News"
bibliography: p-references.bib
---

----

This page documents important updates and additions to the Mplus syntax, *lavaan* code, or the FAQ. 

----

|                        |                                                                                                |
| -----------------------|:-----------------------------------------------------------------------------------------------|
| **July 21st, 2022** | The [FAQ](https://jeroendmulder.github.io/RI-CLPM/faq.html#Standardization) has been updated with information on how to impose constraints such that the *standardized* lagged effects can be made time-invariant. [Mplus](https://jeroendmulder.github.io/RI-CLPM/mplus.html#The_RI-CLPM) and [lavaan](https://jeroendmulder.github.io/RI-CLPM/lavaan.html#The_RI-CLPM) model syntax for specifying such a model have been added as well. |
| **June 28th, 2022** | The answer to the FAQ regarding an RI-CLPM for three or more outcomes has been updated with new examples of researchers applying a trivariate RI-CLPM.|
| **May 17th, 2022** | The FAQ has been updated with a link to the `powRICLPM` R-package. This package is currently developed to allow for user-friendly power analysis for the RI-CLPM. |
| **November 23rd, 2021** | [Residual model syntax specifications for Mplus](https://jeroendmulder.github.io/RI-CLPM/mplus.html#Residual_syntax) have been added, in which the new "hat-notation" of Mplus version 8.7 is used, as well as `PON` and `PWITH` statements to allow for simpler input files. Furthermore, the FAQ was updated with the latest information on [the RI-CLPM for categorical variables](https://jeroendmulder.github.io/RI-CLPM/faq.html#Non-continuous_outcomes), and a new question and answer concerning [development over time](https://jeroendmulder.github.io/RI-CLPM/faq.html#Growth_and_development) in the RI-CLPM was added.|
| **July 7th, 2021** | The [FAQ](https://jeroendmulder.github.io/RI-CLPM/faq.html#Response_to_Orth_et_al_(2021)) has been updated with an informal response to some of the conclusions drawn by Orth et al. (2021) regarding the use and appropriateness of the CLPM and RI-CLPM.

